#
# Run all  checks on PRs and pushes
#
name: Checks

# Controls when the action will run.
on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches: [main, next, beta, alpha]

concurrency:
  group: ${{ github.workflow }}_${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  a11y-checks:
    name: '▶️'
    uses: ./.github/workflows/a11y-checks.yml

  codeql:
    name: '🪲 CodeQL'
    runs-on: ubuntu-latest
    container: node:lts
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python' ]
        # Learn more:
        # https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#changing-the-languages-that-are-analyzed

    steps:
      - name: '☁️ Checkout repository'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: '🧹 Clear previous database' # https://github.com/github/codeql-action/issues/611#issuecomment-872252659
        run: |
          rm -rf "${{ runner.temp }}/codeql_databases/${{ matrix.language }}"

      # Initializes the CodeQL tools for scanning.
      - name: ' 🪡 Initialize CodeQL'
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          db-location: '${{ runner.temp }}/codeql_databases'
          ram:
            8192 # Limite memory usage to 8GB
            # If you wish to specify custom queries, you can do so here or in a config file.
          # By default, queries listed here will override any specified in a config file.
          # Prefix the list here with "+" to use these queries and those in the config file.

          # Details on CodeQL's query packs refer to : https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
          queries: +security-and-quality

      # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
      # If this step fails, then you should remove it and run the build manually (see below)
      - name: '🛠️ Autobuild'
        uses: github/codeql-action/autobuild@v3

      # ℹ️ Command-line programs to run using the OS shell.
      # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun

      #   If the Autobuild fails above, remove it and uncomment the following three lines.
      #   modify them (or add more) to build your code if your project, please refer to the EXAMPLE below for guidance.

      # - run: |
      #   echo "Run, Build Application using script"
      #   ./location_of_script_within_repo/buildscript.sh

      - name: '🕵️ Perform CodeQL Analysis'
        uses: github/codeql-action/analyze@v3
        with:
          category: '/language:${{matrix.language}}'
