#
# Run all  checks on PRs and pushes
#
name: Checks

# Controls when the action will run.
on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches: [main, next, beta, alpha]

concurrency:
  group: ${{ github.workflow }}_${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  a11y-checks:
    name: '▶️'
    uses: ./.github/workflows/a11y-checks.yml
